# Generated by Django 3.2 on 2021-06-20 17:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='login',
            new_name='LoginModel',
        ),
    ]
