# Generated by Django 3.2 on 2021-06-20 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_rename_login_loginmodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='PostModel',
            fields=[
                ('postid', models.IntegerField(max_length=32, primary_key=True, serialize=False)),
                ('topic', models.CharField(max_length=255)),
                ('uid', models.CharField(max_length=64)),
                ('username', models.CharField(max_length=64)),
                ('posttime', models.CharField(max_length=32)),
                ('recent', models.IntegerField(max_length=32)),
                ('number', models.IntegerField(max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='ReplyModel',
            fields=[
                ('replyid', models.IntegerField(primary_key=True, serialize=False)),
                ('postid', models.IntegerField(max_length=32)),
                ('uid', models.CharField(max_length=64)),
                ('username', models.CharField(max_length=64)),
                ('time', models.CharField(max_length=32)),
                ('delete', models.IntegerField(max_length=2)),
                ('order', models.IntegerField(max_length=32)),
                ('content', models.CharField(max_length=255)),
            ],
        ),
    ]
