# Generated by Django 3.2 on 2021-06-20 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0003_postmodel_replymodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.CharField(max_length=64)),
                ('password', models.CharField(max_length=64)),
                ('username', models.CharField(max_length=64)),
            ],
        ),
    ]
