# Generated by Django 3.2 on 2021-06-20 18:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0005_auto_20210621_0214'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usermodel',
            old_name='password',
            new_name='intime',
        ),
    ]
