# Generated by Django 3.2 on 2021-06-22 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0008_remove_postmodel_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='postmodel',
            name='text',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
