# Generated by Django 3.2 on 2021-06-22 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0009_postmodel_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermodel',
            name='birthday',
            field=models.CharField(max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='usermodel',
            name='edress',
            field=models.CharField(max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='usermodel',
            name='gender',
            field=models.CharField(max_length=4, null=True),
        ),
        migrations.AddField(
            model_name='usermodel',
            name='location',
            field=models.CharField(max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='usermodel',
            name='occupation',
            field=models.CharField(max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='usermodel',
            name='phone',
            field=models.CharField(max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='usermodel',
            name='sign',
            field=models.CharField(max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='usermodel',
            name='userintro',
            field=models.CharField(max_length=64, null=True),
        ),
    ]
