# Generated by Django 3.2 on 2021-06-24 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0014_auto_20210624_2205'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermodel',
            name='intime',
            field=models.CharField(max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='usermodel',
            name='username',
            field=models.CharField(max_length=64, null=True),
        ),
    ]
