# Generated by Django 3.2 on 2021-06-24 14:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0015_auto_20210624_2212'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postmodel',
            name='uid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.loginmodel'),
        ),
        migrations.AlterField(
            model_name='replymodel',
            name='postid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.postmodel'),
        ),
        migrations.AlterField(
            model_name='replymodel',
            name='uid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.loginmodel'),
        ),
        migrations.AlterField(
            model_name='usermodel',
            name='uid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='app1.loginmodel'),
        ),
    ]
