# Generated by Django 3.2 on 2021-06-24 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0016_auto_20210624_2218'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postmodel',
            name='uid',
            field=models.CharField(max_length=64),
        ),
        migrations.AlterField(
            model_name='replymodel',
            name='postid',
            field=models.IntegerField(max_length=32),
        ),
        migrations.AlterField(
            model_name='replymodel',
            name='uid',
            field=models.CharField(max_length=64),
        ),
        migrations.AlterField(
            model_name='usermodel',
            name='uid',
            field=models.CharField(max_length=64, primary_key=True, serialize=False),
        ),
    ]
