# Generated by Django 3.2 on 2021-06-30 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0017_auto_20210624_2231'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermodel',
            name='filename',
            field=models.CharField(max_length=64, null=True),
        ),
    ]
