# Generated by Django 3.2 on 2021-07-01 03:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0019_alter_loginmodel_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='replymodel',
            name='postid',
            field=models.IntegerField(),
        ),
    ]
