# Generated by Django 3.2 on 2021-07-05 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0020_alter_replymodel_postid'),
    ]

    operations = [
        migrations.AddField(
            model_name='loginmodel',
            name='identity',
            field=models.CharField(max_length=32, null=True),
        ),
    ]
